package ru.yandex.zen.devel.ssokolviak;

import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

import ru.yandex.bolts.collection.Cf;
import ru.yandex.inside.yt.kosher.cypress.YPath;
import ru.yandex.inside.yt.kosher.impl.ytree.object.annotation.YTreeFlattenField;
import ru.yandex.inside.yt.kosher.impl.ytree.object.annotation.YTreeObject;
import ru.yandex.inside.yt.kosher.ytree.YTreeNode;
import ru.yandex.zen.yt.YtClients;
import ru.yandex.zen.yt.ZenYtCluster;
import ru.yandex.zen.yt.ZenYtConfiguration;
import ru.yandex.zen.yt.dyntable.DyntableInfo;
import ru.yandex.zen.yt.dyntable.DyntableUtils;
import ru.yandex.zen.yt.dyntable.SchemaElem;
import ru.yandex.zen.yt.dyntable.request.DyntableRequestSelectBuilder;
import ru.yandex.zen.yt.dyntable.request.select.DtWhere;
import ru.yandex.zen.yt.dyntable.rpc.MixedDyntableDao;
import ru.yandex.zen.yt.dyntable.rpc.YtRpcClients;

/**
 * DAO for Epistyl CRDT operations storage.
 * <p>
 * Single-table storage for immutable CRDT operations generated by Epistyl.
 * Primary key order is optimized for querying operations by object_id.
 *
 * @author n.d.ivanov
 */
public class OperationDao extends MixedDyntableDao<OperationDao.Key, OperationDao.Entry> {

    private static final String OBJECT_ID_FIELD = "objectId";
    private static final String REPLICA_ID_FIELD = "replicaId";
    private static final String TX_ID_FIELD = "txId";
    private static final String OP_ID_FIELD = "opId";

    private static final List<SchemaElem> SCHEMA =
            DyntableUtils.generateSchemaPreserveKeyColumnOrder(OperationDao.Entry.class,
                    Cf.list(OBJECT_ID_FIELD, REPLICA_ID_FIELD, TX_ID_FIELD, OP_ID_FIELD));


    /**
     * Creates OperationDao for Jupiter cluster at //home/dev/n.d.ivanov/operations
     */
    public OperationDao(YtClients ytClients, YtRpcClients ytRpcClients) {
        super(
                YPath.simple("//home/dev/n.d.ivanov/operations"),
                OperationDao.Key.class,
                OperationDao.Entry.class,
                ytClients.getClient(ZenYtCluster.MIRANDA),
                ytRpcClients
        );
    }

    /**
     * Creates OperationDao with custom path (for testing or other environments)
     */
    public OperationDao(YtClients ytClients, YtRpcClients ytRpcClients, YPath tablePath) {
        super(
                tablePath,
                OperationDao.Key.class,
                OperationDao.Entry.class,
                ytClients.getClient(ZenYtCluster.JUPITER),
                ytRpcClients
        );
    }

    /**
     * Find all operations for a specific CRDT object.
     * Efficient - uses first key column.
     */
    public List<Entry> findByObjectId(String objectId) {
        return findByQuery(requestBuilder()
                .andWhere(DtWhere.eq(OBJECT_ID_FIELD, objectId))
                .build());
    }

    /**
     * Find all operations for a specific object from a specific replica.
     * Efficient - uses first two key columns.
     */
    public List<Entry> findByObjectAndReplica(String objectId, String replicaId) {
        return findByQuery(requestBuilder()
                .andWhere(DtWhere.eq(OBJECT_ID_FIELD, objectId))
                .andWhere(DtWhere.eq(REPLICA_ID_FIELD, replicaId))
                .build());
    }

    /**
     * Find all operations for a specific object, replica, and transaction.
     * Efficient - uses first three key columns.
     */
    public List<Entry> findByObjectReplicaAndTx(String objectId, String replicaId, String txId) {
        return findByQuery(requestBuilder()
                .andWhere(DtWhere.eq(OBJECT_ID_FIELD, objectId))
                .andWhere(DtWhere.eq(REPLICA_ID_FIELD, replicaId))
                .andWhere(DtWhere.eq(TX_ID_FIELD, txId))
                .build());
    }

    /**
     * Find operations for an object filtered by action path prefix.
     * Loads all operations for the object, then filters by path prefix in memory.
     * Useful for finding all operations on a specific field or nested path.
     *
     * @param objectId Object ID to search
     * @param pathPrefix Path prefix to match (e.g., ["event-0", "title"] matches all operations on title field)
     * @return List of entries whose action path starts with the given prefix
     */
    public List<Entry> findByObjectIdAndPath(String objectId, List<String> pathPrefix) {
        List<Entry> allOps = findByObjectId(objectId);
        return allOps.stream()
                .filter(entry -> {
                    List<String> entryPath = entry.getAction().getPath();
                    if (entryPath.size() < pathPrefix.size()) {
                        return false;
                    }
                    for (int i = 0; i < pathPrefix.size(); i++) {
                        if (!entryPath.get(i).equals(pathPrefix.get(i))) {
                            return false;
                        }
                    }
                    return true;
                })
                .toList();
    }

    @Override
    protected List<SchemaElem> getSchema() {
        return SCHEMA;
    }

    @Override
    protected DyntableInfo info() {
        return new DyntableInfo.Builder()
                .setTablePath(path)
                .setSchema(getSchema())
                .build();
    }

    /**
     * Composite key for Epistyl operation.
     * Order is optimized for querying by object_id first.
     */
    @YTreeObject
    public static class Key {
        private final String objectId;
        private final String replicaId;
        private final String txId;
        private final String opId;

        public Key(String objectId, String replicaId, String txId, String opId) {
            this.objectId = objectId;
            this.replicaId = replicaId;
            this.txId = txId;
            this.opId = opId;
        }

        public String getObjectId() {
            return objectId;
        }

        public String getReplicaId() {
            return replicaId;
        }

        public String getTxId() {
            return txId;
        }

        public String getOpId() {
            return opId;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Key key = (Key) o;
            return Objects.equals(objectId, key.objectId)
                    && Objects.equals(replicaId, key.replicaId)
                    && Objects.equals(txId, key.txId)
                    && Objects.equals(opId, key.opId);
        }

        @Override
        public int hashCode() {
            return Objects.hash(objectId, replicaId, txId, opId);
        }

        @Override
        public String toString() {
            return "Key{" +
                    "objectId='" + objectId + '\'' +
                    ", replicaId='" + replicaId + '\'' +
                    ", txId='" + txId + '\'' +
                    ", opId='" + opId + '\'' +
                    '}';
        }
    }

    /**
     * Epistyl operation entry.
     * Each row represents exactly one immutable Epistyl operation.
     */
    @YTreeObject
    public static class Entry {
        @YTreeFlattenField
        private final Key key;

        private final Map<String, Long> clock;
        private final Action action;

        public Entry(Key key, Map<String, Long> clock, Action action) {
            this.key = key;
            this.clock = clock;
            this.action = action;
        }

        public Key getKey() {
            return key;
        }

        /**
         * Vector clock snapshot stored inside Epistyl operation.
         * Mapping from replicaId to logical counter.
         * Used for causal ordering, concurrency detection, and operation comparison.
         */
        public Map<String, Long> getClock() {
            return clock;
        }

        /**
         * Serialized domain action stored inside Epistyl operation.
         * Concrete CRDT mutation applied to object path.
         */
        public Action getAction() {
            return action;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Entry entry = (Entry) o;
            return Objects.equals(key, entry.key)
                    && Objects.equals(clock, entry.clock)
                    && Objects.equals(action, entry.action);
        }

        @Override
        public int hashCode() {
            return Objects.hash(key, clock, action);
        }

        @Override
        public String toString() {
            return "Entry{" +
                    "key=" + key +
                    ", clock=" + clock +
                    ", action=" + action +
                    '}';
        }
    }

    /**
     * Epistyl action - concrete CRDT mutation applied to object path.
     * <p>
     * Action types:
     * - field.set: Set field value
     * - field.delete: Delete field
     * - set.add: Add value to set
     * - set.remove: Remove value from set
     * - array.insert: Insert value at index
     * - array.remove: Remove value at index
     * - node.initObject: Initialize object node
     * - node.initSet: Initialize set node
     * - node.initArray: Initialize array node
     */
    @YTreeObject
    public static class Action {
        private final String type;
        private final List<String> path;
        private final Optional<YTreeNode> value;
        private final Optional<Long> index;

        /**
         * Create action with value (field.set, set.add, array.insert)
         */
        public Action(String type, List<String> path, YTreeNode value) {
            this.type = type;
            this.path = path;
            this.value = Optional.ofNullable(value);
            this.index = Optional.empty();
        }

        /**
         * Create action with index (array.insert, array.remove)
         */
        public Action(String type, List<String> path, YTreeNode value, Long index) {
            this.type = type;
            this.path = path;
            this.value = Optional.ofNullable(value);
            this.index = Optional.ofNullable(index);
        }

        /**
         * Create action without value (field.delete, node.init*)
         */
        public Action(String type, List<String> path) {
            this.type = type;
            this.path = path;
            this.value = Optional.empty();
            this.index = Optional.empty();
        }

        /**
         * Full constructor for YTree deserialization
         */
        public Action(String type, List<String> path, Optional<YTreeNode> value, Optional<Long> index) {
            this.type = type;
            this.path = path;
            this.value = value;
            this.index = index;
        }

        /**
         * Action type (e.g., "field.set", "set.add", "array.insert")
         */
        public String getType() {
            return type;
        }

        /**
         * Path to target node or field inside composite CRDT object.
         * Each element is a string representing field name or path segment.
         */
        public List<String> getPath() {
            return path;
        }

        /**
         * Value for actions that require it (field.set, set.add, array.insert)
         */
        public Optional<YTreeNode> getValue() {
            return value;
        }

        /**
         * Index for array operations
         */
        public Optional<Long> getIndex() {
            return index;
        }

        @Override
        public boolean equals(Object o) {
            if (this == o) return true;
            if (o == null || getClass() != o.getClass()) return false;
            Action action = (Action) o;
            return Objects.equals(type, action.type)
                    && Objects.equals(path, action.path)
                    && Objects.equals(value, action.value)
                    && Objects.equals(index, action.index);
        }

        @Override
        public int hashCode() {
            return Objects.hash(type, path, value, index);
        }

        @Override
        public String toString() {
            return "Action{" +
                    "type='" + type + '\'' +
                    ", path=" + path +
                    ", value=" + value +
                    ", index=" + index +
                    '}';
        }
    }
}